CREATE DATABASE ps2;
USE ps2;

CREATE TABLE usuario (
	idUsuario INT PRIMARY KEY AUTO_INCREMENT,
	nomeUsuario VARCHAR(45) NOT NULL,
    apelidoUsuario VARCHAR(45),
	email VARCHAR(45) NOT NULL,
	senha VARCHAR(45) NOT NULL,
    fkJogo INT,
    FOREIGN KEY (fkJogo) REFERENCES jogo(idJogo)
);

CREATE TABLE jogo (
	idJogo INT PRIMARY KEY AUTO_INCREMENT,
	nomeJogo VARCHAR(70) NOT NULL,
    sinopse VARCHAR(255) NOT NULL,
	qtdVotos INT
); 